# 2.Control Flow and Error Handling

## 📍Block Statement
```javascript
  {
    statement_1;
    statement_2;
    .
    .
    .
    statement_n;
  }
```
### **Block Scope**

- ES6 이전의 JS에는 block scope를 가지지 않았습니다!
    - 이전의 JS에서는 block 안의 variable은 function, script 단위로 scope 되었기 때문에 block을 넘어서도 영향을 끼칠수 있었습니다. *즉, block statement는 scope를 결정짓지 않았죠.*
    - 'Standalone' block은 C나 Java와는 전혀 다른 결과를 만들어냅니다.
    
```javascript
  var x = 1;
  {
    var x = 2;
  }
  console.log(x); // outputs 2
```
위 코드에서 C,Java는 `1` 이라는 결과를 내겠지만 JS에서는 블록안의 `var x` statement가 block 밖의 `var x` 와 같은 스코프를 가지기 때문에 `2`라는 결과를 만들어냅니다. 

- **ES6 에서는 block scope를 가지는  `let`, `const` 변수를 가지게 되었습니다.**

<br>

## 📍Conditional Statement

- JS는 `if...else` 와 `switch` 2가지 형태의 조건문을 지원합니다.

### `if...else`  statement
```javascript
  if (condition) { //condition은 true 혹은 false의 값을 만들어내는 표현식입니다.
    statement_1;
  } else if (condition_n) {
    statement_n;
  } else {
    statement_last;
  }
```

- Falsy values 를 제외한 모든 값은 `true` 입니다.
```javascript
  //Falsy values
  false
  undefined
  null
  0
  NaN
  "" //empty string
```
- *boolean value `true` `false` 와 `Boolean` Object를 혼동하여 사용하지 마세요!*
```javascript
  var b = new Boolean(false);
  if (b)         // this condition evaluates to true
  if (b == true) // this condition evaluates to false
```

### `Switch` statement

- 주의) `break` statement를 명시하지 않으면 프로그램은 다음 line을 계속해서 실행하게 됩니다.
```javascript
  switch (expression) {
    case label_1:
      statements_1
      [break;]
    case label_2:
      statements_2
      [break;]
      ...
    default:
      statements_def
      [break;]
  }
```

<br>

## 📍Exception Handling Statements

- `throw` statment를 통해 exception을 발생시키고, `try...catch` 를 통해 핸들링 할수 있습니다.

### Exception types

- 보통 number 나 string으로 exception을 발생시키지만, exception type을 통해 더욱 효율적으로 사용할 수 있습니다.
- [`ECMAScript exceptions`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#Error_types)
- [`DOMException`](https://developer.mozilla.org/en-US/docs/Web/API/DOMException) and [`DOMError`](https://developer.mozilla.org/en-US/docs/Web/API/DOMError)

### `throw` statement
```javascript
  throw 'Error2';   // String type
  throw 42;         // Number type
  throw true;       // Boolean type
  throw {toString: function() { return "I'm an object!"; } };
```

- Object 를 통해 예외를 발생시킬 수 있고 `catch` 블록에서 object의 프로퍼티를 참조하여 사용할 수 있습니다.
```javascript
  // Create an object type UserException
  function UserException(message) {
    this.message = message;
    this.name = 'UserException';
  }

  // Make the exception convert to a pretty string when used as a string 
  // (e.g. by the error console)
  UserException.prototype.toString = function() {
    return this.name + ': "' + this.message + '"';
  }

  // Create an instance of the object type and throw it
  throw new UserException('Value too high');
```

### `try...catch` statement
```javascript
  function getMonthName(mo) {
    mo = mo - 1; // Adjust month number for array index (1 = Jan, 12 = Dec)
    let months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul',
                  'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    if (months[mo]) {
      return months[mo];
    } else {
      throw 'InvalidMonthNo'; //throw keyword is used here
    }
  }

  try { // statements to try
    monthName = getMonthName(myMonth); // function could throw exception
  }
  catch (e) {
    monthName = 'unknown';
    logMyErrors(e); // pass exception object to error handler -> your own function
  }
```

### `finally` block

- `try`,catch 블록 이후에 항상 실행되는 부분입니다.
```javascript
  openMyFile();
  try {
    writeMyFile(theData); //This may throw an error
  } catch(e) {  
    handleError(e); // If we got an error we handle it
  } finally {
    closeMyFile(); // always close the resource
  }
```
